register:
    path:      /register
    controller: App\Controller\RegisterController::index

store_user:
    path: /register/user
    controller: App\Controller\RegisterController::store

login_user:
    path: /login
    controller: App\Controller\LoginController::index