register:
    path:      /register
    controller: App\Controller\RegisterController::index

store_user:
    path: /register/user
    controller: App\Controller\RegisterController::store

login_user:
    path: /login
    controller: App\Controller\LoginController::index

logout_user:
    path: /logout
    methods: GET

show_records:
    path: /records/{id}
    controller: App\Controller\RecordController::show

delete_record:
    path: /records/delete/{id}
    controller: App\Controller\RecordController:delete

store_record:
    path: /records/user/{id}
    controller: App\Controller\RecordController::store

all_users:
    path: /users
    controller: App\Controller\UserController::index