register:
    path:      /register
    controller: App\Controller\RegisterController::index

store_user:
    path: /register/user
    controller: App\Controller\RegisterController::store

login_user:
    path: /login
    controller: App\Controller\LoginController::index

logout_user:
    path: /logout
    methods: GET

show_records:
    path: /records/{userId}
    controller: App\Controller\RecordController::show

my_records:
    path: /my_records
    controller: App\Controller\RecordController::myRecords

store_record:
    path: /records/user/{userId}
    controller: App\Controller\RecordController::store

edit_record:
    path: /records/edit/{recordId}
    controller: App\Controller\RecordController::edit

put_record:
    path: /records/put/{recordId}
    controller: App\Controller\RecordController::put

delete_record:
    path: /records/delete/{recordId}
    controller: App\Controller\RecordController:delete

all_users:
    path: /users
    controller: App\Controller\UserController::index

edit_role:
    path: /user/{id}/role
    controller: App\Controller\UserController::upgrade